export const SET_START_CAMERA = "SET_START_CAMERA";
export const TAKE_PICTURE = "TAKE_PICTURE";
export const SAVE_PICTURE = "SAVE_PICTURE"
export const SET_PREVIEW_VISIBLE = "SET_PREVIEW_VISIBLE"
export const SET_CAPTURED_IMAGE = "SET_CAPTURED_IMAGE"

