const amosData = {
  cat: {
    id: 1,
    type: "mammal",
    species: "cat",
    name: "cat",
    level: 1,
  },
  dog: {
    id: 2,
    type: "mammal",
    species: "dog",
    name: "dog",
    level: 1,
  },
  squirrel: {
    id: 3,
    type: "mammal",
    species: "squirrel",
    name: "squirrel",
    level: 1,
  },
  pigeon: {
    id: 4,
    type: "bird",
    species: "pigeon",
    name: "pigeon",
    level: 1,
  },
  seagull: {
    id: 5,
    type: "bird",
    species: "seagull",
    name: "seagull",
    level: 1,
  },
  goeland: {
    id: 6,
    type: "bird",
    species: "goeland",
    name: "goeland",
    level: 1,
  },
  cormoran: {
    id: 7,
    type: "bird",
    species: "cormoran",
    name: "cormoran",
    level: 1,
  },
  turtle: {
    id: 8,
    type: "reptile",
    species: "turtle",
    name: "turtle",
    level: 1,
    date: "",
  },
  frog: {
    id: 9,
    type: "amphibian",
    species: "frog",
    name: "frog",
    level: 1,
  },
  snail: {
    id: 10,
    type: "invertebrate",
    species: "snail",
    name: "snail",
    level: 1,
  },
  hen: {
    id: 11,
    type: "bird",
    species: "hen",
    name: "hen",
    level: 1,
  },
  rooster: {
    id: 12,
    type: "bird",
    species: "rooster",
    name: "rooster",
    level: 1,
  },
  duck: {
    id: 13,
    type: "bird",
    species: "duck",
    name: "duck",
    level: 1,
  },
  goose: {
    id: 13,
    type: "bird",
    species: "duck",
    name: "duck",
    level: 1,
  },
  cow: {
    id: 14,
    type: "mammal",
    species: "cow",
    name: "cow",
    level: 1,
  },
  bull: {
    id: 15,
    type: "mammal",
    species: "bull",
    name: "bull",
    level: 1,
  },
  sheep: {
    id: 16,
    type: "mammal",
    species: "sheep",
    name: "sheep",
    level: 1,
  },
  goat: {
    id: 17,
    type: "mammal",
    species: "goat",
    name: "goat",
    level: 1,
  },
  pig: {
    id: 18,
    type: "mammal",
    species: "pig",
    name: "pig",
    level: 1,
  },
};

export default amosData;
