const amosData = {
  // temporary =>
  cat: {
    id: 1,
    type: "Mammifère",
    species: "Chat",
    name: "Chat",
    level: 1,
    date: "",
  },
  dog: {
    id: 2,
    type: "Mammifère",
    species: "Chien",
    name: "Chien",
    level: 1,
    date: "",
  },
  squirrel: {
    id: 3,
    type: "Mammifère",
    species: "Ecureuil",
    name: "Ecureuil",
    level: 1,
    date: "",
  },
  pigeon: {
    id: 4,
    type: "Oiseau",
    species: "Pigeon",
    name: "Pigeon",
    level: 1,
    date: "",
  },
  seagull: {
    id: 5,
    type: "Oiseau",
    species: "Mouette",
    name: "Mouette",
    level: 1,
    date: "",
  },
  goeland: {
    id: 6,
    type: "Oiseau",
    species: "Goeland",
    name: "Goeland",
    level: 1,
    date: "",
  },
  cormoran: {
    id: 7,
    type: "Oiseau",
    species: "Cormoran",
    name: "Cormoran",
    level: 1,
    date: "",
  },
  turtle: {
    id: 8,
    type: "Reptile",
    species: "Turtle",
    name: "Turtle",
    level: 1,
    date: "",
  },
  frog: {
    id: 9,
    type: "Amphibien",
    species: "Grenouille",
    name: "Grenouille",
    level: 1,
    date: "",
  },
  snail: {
    id: 10,
    type: "Invertébré",
    species: "Escargot",
    name: "Escargot",
    level: 1,
    date: "",
  },
};

export default amosData;
