// Temp data to fill the Archamos with some Amos
// To serialize with Amos.ts

import amosTmpImgs from "../../assets/amosTmpImgs";

const amosList = [
  {
    idAmos: 5,
    idOwner: "DaUser",
    id: 1,
    imagePath: amosTmpImgs.cat,
    type: "mammal",
    species: "cat",
    name: "Pitichat",
    level: 22,
    date: "",
  },
  {
    idAmos: 12,
    idOwner: "DaUser",
    id: 2,
    imagePath: amosTmpImgs.dog,
    type: "mammal",
    species: "dog",
    name: "Groddog",
    level: 10,
    date: "",
  },
  {
    idAmos: 44,
    idOwner: "DaUser",
    id: 3,
    imagePath: amosTmpImgs.squirrel,
    type: "mammal",
    species: "squirrel",
    name: "Cureuil",
    level: 10,
    date: "",
  },
  {
    idAmos: 64,
    idOwner: "DaUser",
    id: 4,
    imagePath: amosTmpImgs.frog,
    type: "amphibian",
    species: "frog",
    name: "Froggy",
    level: 55,
    date: "",
  },
  {
    idAmos: 55,
    idOwner: "DaUser",
    id: 5,
    imagePath: amosTmpImgs.snail,
    type: "invertebrate",
    species: "snail",
    name: "Treland",
    level: 2,
    date: "",
  },
  {
    idAmos: 88,
    idOwner: "DaUser",
    id: 6,
    imagePath: amosTmpImgs.turtle,
    type: "reptile",
    species: "turtle",
    name: "Tankuy",
    level: 60,
    date: "",
  },
  {
    idAmos: 77,
    idOwner: "DaUser",
    id: 7,
    imagePath: amosTmpImgs.bird,
    type: "bird",
    species: "seagull",
    name: "Seagal",
    level: 10,
    date: "",
  },
  {
    idAmos: 45,
    idOwner: "DaUser",
    id: 8,
    imagePath: amosTmpImgs.cormoran,
    type: "bird",
    species: "cormoran",
    name: "Cormaran",
    level: 45,
    date: "",
  },
];

export default amosList;
